const prefix = 'CHAT_';

export default {
  FETCH_MESSAGES: `${prefix}FETCH_MESSAGES`,
  FETCH_MESSAGES_COMPLETED: `${prefix}FETCH_MESSAGES_COMPLETED`,
  MESSAGE_ADDED: `${prefix}MESSAGE_ADDED`,
  CREATE_MESSAGE: `${prefix}CREATE_MESSAGE`,
  CREATE_MESSAGE_COMPLETED: `${prefix}CREATE_MESSAGE_COMPLETED`,
  FETCH_PARTICIPANTS: `${prefix}FETCH_PARTICIPANTS`,
  FETCH_PARTICIPANTS_COMPLETED: `${prefix}FETCH_PARTICIPANTS_COMPLETED`,
  RAISE_HAND: `${prefix}RAISE_HAND`,
  RAISE_HAND_COMPLETED: `${prefix}RAISE_HAND_COMPLETED`,
  ADD_MESSAGE: `${prefix}ADD_MESSAGE`,
};
