const prefix = 'BOOKMARKS_';

export default {
  FETCH_BOOKMARKS: `${prefix}FETCH_BOOKMARKS`,
  FETCH_BOOKMARKS_COMPLETED: `${prefix}FETCH_BOOKMARKS_COMPLETED`,

  ADD_BOOKMARK: `${prefix}ADD_BOOKMARK`,
  ADD_BOOKMARK_COMPLETED: `${prefix}ADD_BOOKMARK_COMPLETED`,
};
