const prefix = 'ROOM_';

export default {
  FETCH_PARTICIPANTS: `${prefix}FETCH_PARTICIPANTS`,
  FETCH_PARTICIPANTS_COMPLETED: `${prefix}FETCH_PARTICIPANTS_COMPLETED`,
  RAISE_HAND: `${prefix}RAISE_HAND`,
  RAISE_HAND_COMPLETED: `${prefix}RAISE_HAND_COMPLETED`,

  MUTE: `${prefix}MUTE`,
  MUTE_COMPLETED: `${prefix}MUTE_COMPLETED`,

  MUTE_ALL: `${prefix}MUTE_ALL`,
  MUTE_ALL_COMPLETED: `${prefix}MUTE_ALL_COMPLETED`,

  SET_MET_AS_MUTED: `${prefix}SET_MET_AS_MUTED`,

  KICK: `${prefix}KICK`,
  KICK_COMPLETED: `${prefix}KICK_COMPLETED`,

  CHECK_MY_PARTICIPANT: `${prefix}CHECK_MY_PARTICIPANT`,
  CHECK_MY_PARTICIPANT_COMPLETED: `${prefix}CHECK_MY_PARTICIPANT_COMPLETED`,

  SET_ROOM_OWNER: `${prefix}SET_ROOM_OWNER`,
  SET_ROOM_USER_ID: `${prefix}SET_ROOM_USER_ID`,
  SET_ROOM_USER_ID_COMPLETED: `${prefix}SET_ROOM_USER_ID_COMPLETED`,
  SET_ROOM_OWNER_COMPLETED: `${prefix}SET_ROOM_OWNER_COMPLETED`,

  SET_IN_ROOM: `${prefix}SET_IN_ROOM`,
  SET_IN_ROOM_COMPLETED: `${prefix}SET_IN_ROOM_COMPLETED`,
};
