const prefix = 'USER_PROFILE_';

export default {
  FETCH_USER_PROFILE: `${prefix}FETCH_USER_PROFILE`,
  FETCH_USER_PROFILE_COMPLETED: `${prefix}FETCH_USER_PROFILE_COMPLETED`,
  SAVE: `${prefix}SAVE`,
  SAVE_COMPLETED: `${prefix}SAVE_COMPLETED`,

  UPLOAD_USER_IMAGE: `${prefix}UPLOAD_USER_IMAGE`,
  UPLOAD_USER_LOGO_IMAGE: `${prefix}UPLOAD_USER_LOGO_IMAGE`,
  UPLOAD_USER_BACKGROUND_IMAGE: `${prefix}UPLOAD_USER_BACKGROUND_IMAGE`,
  UPLOAD_USER_IMAGE_COMPLETED: `${prefix}UPLOAD_USER_IMAGE_COMPLETED`,
  UPLOAD_USER_LOGO_IMAGE_COMPLETED: `${prefix}UPLOAD_USER_LOGO_IMAGE_COMPLETED`,
  UPLOAD_USER_BACKGROUND_IMAGE_COMPLETED: `${prefix}UPLOAD_USER_BACKGROUND_IMAGE_COMPLETED`,
};
