const prefix = 'USER_ORDERS_';

export default {
  FETCH_USER_REFERRERS: `${prefix}FETCH_USER_REFERRERS`,
  FETCH_USER_REFERRERS_SECOND_LEVEL: `${prefix}FETCH_USER_REFERRERS_SECOND_LEVEL`,
  FETCH_USER_REFERRERS_THIRD_LEVEL: `${prefix}FETCH_USER_REFERRERS_THIRD_LEVEL`,
  FETCH_USER_REFERRERS_COMPLETE: `${prefix}FETCH_USER_REFERRERS_COMPLETE`,
  FETCH_USER_REFERRERS_SECOND_LEVEL_COMPLETE: `${prefix}FETCH_USER_REFERRERS_SECOND_LEVEL_COMPLETE`,
  FETCH_USER_REFERRERS_THIRD_LEVEL_COMPLETE: `${prefix}FETCH_USER_REFERRERS_THIRD_LEVEL_COMPLETE`,
};
