version: '3.7'
services:
  db:
    image: bitnami/mongodb:4.2.8
    ports:
      - 27017:27017
    volumes:
      - db:/bitnami/mongodb—Å
    networks:
      - backend
    environment:
      MONGODB_ROOT_PASSWORD: admin
      MONGODB_USERNAME: avikast
      MONGODB_PASSWORD: admin
      MONGODB_DATABASE: avikast
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_ADVERTISED_HOSTNAME: db
      MONGODB_REPLICA_SET_KEY: avikastrs0
  backend:
    image: avikast-backend
    build: .
    networks:
      - backend
    depends_on:
      - db
    ports:
      - 80:3080
      - 443:3443
    environment:
      NODE_ENV: testing
      DATABASE_HOST: db
      DATABASE_PORT: 27017
      DATABASE_USERNAME: avikast
      DATABASE_PASSWORD: admin
      DATABASE_NAME: avikast
volumes:
  db:
networks:
  backend:
