const prefix = 'ROOM_';

export default {
  CREATE_ROOM_OPTIONS: `${prefix}CREATE_ROOM_OPTIONS`,
  JOIN_ROOM_OPTIONS: `${prefix}JOIN_ROOM_OPTIONS`,
  JOIN_ROOM_COMPLETED: `${prefix}JOIN_ROOM_COMPLETED`,
  CREATE_ROOM_COMPLETED: `${prefix}CREATE_ROOM_COMPLETED`,
  INITIALIZE_WEBINAR: `${prefix}INITIALIZE_WEBINAR`,
  RECEIVE_STREAM: `${prefix}RECEIVE_STREAM`,
  GET_ROOM_TRACKS: `${prefix}GET_ROOM_TRACKS`,

  FETCH_ROOM: `${prefix}FETCH_ROOM`,
  FETCH_ROOM_COMPLETED: `${prefix}FETCH_ROOM_COMPLETED`,

  LEAVE_ROOM: `${prefix}LEAVE_ROOM`,
  LEAVE_ROOM_COMPLETED: `${prefix}LEAVE_ROOM_COMPLETED`,

  CLOSE_ROOM: `${prefix}CLOSE_ROOM`,
  CLOSE_ROOM_COMPLETED: `${prefix}CLOSE_ROOM_COMPLETED`,

  GET_ROOM: `${prefix}GET_ROOM`,
  GET_ROOM_COMPLETED: `${prefix}GET_ROOM_COMPLETED`,

  CHECK_IS_CLOSED: `${prefix}CHECK_IS_CLOSED`,
  CHECK_IS_CLOSED_COMPLETED: `${prefix}CHECK_IS_CLOSED_COMPLETED`,
};
