const prefix = 'RESUME_';

export default {
  SAVE_USER_RESUME: `${prefix}SAVE_USER_RESUME`,
  SAVE_USER_RESUME_COMPLETED: `${prefix}SAVE_USER_RESUME_COMPLETED`,
  FETCH_USER_RESUME: `${prefix}FETCH_USER_RESUME`,
  FETCH_USER_RESUME_COMPLETED: `${prefix}FETCH_USER_RESUME_COMPLETED`,

  FETCH_USER_RESUME_LINK: `${prefix}FETCH_USER_RESUME_LINK`,
  FETCH_USER_RESUME_LINK_COMPLETED: `${prefix}FETCH_USER_RESUME_LINK_COMPLETED`,

  UPLOAD_PDF: `${prefix}UPLOAD_PDF`,
  UPLOAD_PDF_COMPLETED: `${prefix}UPLOAD_PDF_COMPLETED`,
};
